version: '3'
services:

  resources-booking.host:
    container_name: resources-booking.host
    image: ponomnikita/resource-booking:latest
    ports:
    - 5000:80
    - 5001:443
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Resources=Host=postgres;Username=rb;Password=P@ssw0rd;Database=resources;Pooling=true;
    volumes:
      - ${HOME}/.aspnet/https:/https/
      - ./data:/app/data

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: rb
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - 5432:5432
    restart: unless-stopped