version: '3'
services:

  resources-booking.host:
    container_name: resources-booking.host
    image: ponomnikita/resource-booking:latest
    ports:
    - 80:80
    - 443:443
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
      - ConnectionStrings__Resources=Host=postgres;Username=rb;Password=P@ssw0rd;Database=resources;Pooling=true;
      - gitlab__clientId=<clientId>
      - gitlab__clientSecret=<clientSecret>
      - gitlab__authEndpoint=https://gitlab.com/oauth/authorize
      - gitlab__tokenEndpoint=https://gitlab.com/oauth/token
      - gitlab__userInfoEndpoint=https://gitlab.com/api/v4/user
    volumes:
      - ./https:/https/
      - ./data:/app/data

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: rb
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - 5432:5432
    restart: unless-stopped